---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*
    - lib/route_translator/core_ext/mapper_patch.rb
    - lib/route_translator/core_ext/route_set_patch.rb

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

#########
# RAILS #
#########

Rails:
  Enabled: true

##########
# LAYOUT #
##########

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

#########
# STYLE #
#########

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

###########
# METRICS #
###########

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ClassLength:
  Max: 120
